### 목표
    - 붓꽃의 꽃잎 길이, 너비/ 꽃받침 길이, 너비 특징 4개를 활용하여 3가지의 붓꽃품종을 분류해보자
    - knn모델의 이웃의 수를 조정해보자(n_neighbors개수를 조정, k의 개수를 조정, k ==n_neighbors): 하이퍼 파라미터 튜닝

In [3]:
# 환경
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 머신러닝
from sklearn.neighbors import KNeighborsClassifier  #분류
from sklearn.metrics import accuracy_score  #평가
#train,test set 분리
from sklearn.model_selection import train_test_split   

# 데이터 불러오기
from sklearn.datasets import load_iris #붓꽃데이터 가져오기


In [9]:
# iris 데이터 열어 확인
iris_data = load_iris()
iris_data   # 딕셔너리 형식으로 데이터가 담김 -> sklearn.datasets
# 번처(bunch)객치

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [14]:
# 딕셔너리 key값만 확인
# items(), values(), keys()
iris_data.keys()
# data : X, 문제, 독립변수, 설명변수, 특성, feature
# target : y, 답, 종속변수, 반응변수, label, 라벨
# - 분류용 답 : 카테고리 label, class label
# feature_names : 특성의 이름들
# target_names : 답데이터 이름들
# DESCR : 기술통계, 데이터 정보(크기, 상관관계, 출처)
# 필수적 입력 데이터 : data, target
# 옵션 데이터 : feature_names, target_names, DESCR, frame, filename....


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [23]:
# 문제 데이터 살펴보기

# 키 data 값만 가져오는 방법 두가지 iris_data['data'], iris_data.data
# iris_data['data']
print(iris_data.data)
print(iris_data.data.shape) # 크기
print(iris_data.data.dtype) # data타입
print(iris_data.data.ndim) # 차원


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [29]:
# 문제 데이터
iris_data.data[0:5] # 5개 행 출력



array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [30]:
# 특성의 이름 확인하기
iris_data.feature_names

# sepal length (cm) : 꽃받침 길이
# sepal width (cm) : 꽃받침 너비
# petal length (cm) : 꽃잎 길이
# petal width (cm) : 꽃잎 너비
# 총 4개의 특성으로 붓꽃 품종을 분류해보는 상황

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [26]:
# 답 데이터 살펴보기

iris_data.target
# 클래스(카테고리) class : 3개

# 1. 섞기 2.분할 7:3 -> train_test_split


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
# 품종이름
iris_data.target_names
# setosa -0
# versicolor -1
# virginica -2


array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [35]:
# DESCR : 기술통계량 확인

print(iris_data.DESCR)

# Class Correlation 클래스와  상관관계
# -1~1 표현되는 상관계수
# -1, +1 가까울수록 상관이 어느정도 높음
#  0가까울 수록 상관관계가 덜함(적음)
# (high!) : petal width, petal length 2개의 컬럼이
# 3가지 품종을 분휴하는데 도움을 주고 있음, 유의미한 컬럼


.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

#### 데이터셋 구성
    - numpy -> 특성데이터(피처, 문제)만 df 변경
    - X, y
    - traub_test_split도구를 활용해서 train set, test set구성

In [48]:
iris_df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris_df.head(8)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2

In [54]:
# 문제와 답변수 정리
X = iris_df
y = iris_data.target
# 데이터의 균형 - 다양성이 나름대로 유지가 된 데이터
np.unique(y,return_counts=True)

(array([0, 1, 2]), array([50, 50, 50], dtype=int64))

In [ ]:
# train_test_split 도구 활용
X_train, X_test, y_train, y_test